### ISSUE TITLE
Release Leniax in OpenSource

### ISSUE THREAD

**Issue by morgangiraud** [morgangiraud/leniax#13]
TODO:
- #15 
- #24 
- #28 
- #30 
- [x] Clean all files
- [x] Improve Readme.md
- [x] Write a blog post showing the capabilities
- [x] Write a twitter thread

Goals of Leniax:
- Provide a single codebase to simulate cellular automata from CGOL to Neural Lenia
- Easily and efficiently run a Lenia simulation
- Easily and efficiently run a creature search
- Easily and efficiently optimize any inputs of the pipeline
- Easily and efficiently visualize results
